# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-devops
  labels:
    app: go-app-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app-devops
  template:
    metadata:
      labels:
        app: go-app-devops
    spec:
      containers:
      - name: go-app-devops
        image: nilesh9/go-app-devops:v1
        ports:
        - containerPort: 8080